CustomerCarePortal/Pages/Tracking/Index.cshtml.cs
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CustomerCarePortal.Pages.Tracking
{
    public class IndexModel : PageModel
    {
        public ApplicationDbContext _db;
        [BindProperty]
        public Ticket Ticket { get; set; } = default!; [BindProperty]
        public Comment comment { get; set; } = default!;
        public List<Comment> Comments { get; set; } = default!;
        public Boolean Flag { get; set; } = true;
        public string ID { get; set; } = "";
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id is not null)
            {
                ID = id;
                var ticket = _db.Tickets
                    .Include(t => t.History)
                    .FirstOrDefault(t => t.TrackingId.Equals(id));
                if (ticket is not null)
                {
                    Flag = false;
                    ticket.CurrentState = await _db.States.FindAsync(ticket.CurrentStateId);
                    Comments = await _db.Comments
                        .Where(c => c.HistoryId == ticket.History.Id)
                        .OrderByDescending(c=>c.Id)
                        .ToListAsync();
                    Ticket = ticket;
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostTrack()
        {
            if (Ticket is not null)
            {
                return RedirectToPage("/Tracking/Index", new { id = Ticket.TrackingId });
            }
            else
            {
                return Page();
            }
        }

        public async Task<IActionResult> OnPostAddComment()
        {
            try
            {
                if (comment.Description != null && comment.Description.Trim() != "")
                {
                    string description = DateTime.Now.ToLocalTime().ToString() + ": " + Ticket.Email + ": " + comment.Description;
                    comment.Description = description;
                    comment.HistoryId = Ticket.History.Id;
                    await _db.Comments.AddAsync(comment);
                    await _db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
            return RedirectToPage("/Tracking/Index", new { id = Ticket.TrackingId });
        }
    }
}

CustomerCarePortal/Pages/Tracking/Index.cshtml
@page
@model CustomerCarePortal.Pages.Tracking.IndexModel
@{
}
<div class="row col-12 justify-content-center text-capitalize fs-1">Tracking Page</div>
<h3>Enter your Tracking id: </h3>
<form class="form-inline row" asp-page-handler="Track">
    <div class="input-group">
        <input asp-for="Ticket.TrackingId" class="form-control py-2 border-right-0 border w-25" placeholder="Type Tracking Id" id="example-search-input" required>
        <span class="input-group-append w-75">
            <button class="btn btn-primary btn-outline-light border-left-0 border" type="submit">
                <i class="bi bi-search"></i>
            </button>
        </span>
    </div>
</form>


@if (@Model.Flag)
{
    @if (!@Model.ID.Equals(""))
    {
        <div class="text-danger fs-2 text-capitalize"> No Match Found against tracking id: @Model.ID</div>
    }
}
else
{
    if (@Model.Ticket is not null)
    {
        <div class="mt-3 row">
            <div class="col-md-6 card" >
                <div class="card-body">
                    <h5 class="card-title">@Model.Ticket.Email</h5>
                    <p class="card-text">@Model.Ticket.Description</p>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Current Status</h5>
                    @if (@Model.Ticket.CurrentState is not null)
                    {
                        <p class="card-text fw-bold">@Model.Ticket.CurrentState.Name</p>
                    }
                    else
                    {
                        <p class="card-text fw-bold">Please be patient while we assign some team to work on ticket :)</p>
                    }
                </div>
            </div>
            <!-- Comment History-->
            <div class="col-md-6 row">
                <div class="col-12 ">
                    <h4>Edit History</h4>
                    <div class="card" style="width: 100%;overflow:scroll;height:300px;">
                        <ul class="list-group list-group-flush">
                            @if (@Model.Comments is not null)
                            {
                                @foreach (var comment in @Model.Comments)
                                {
                                    <li class="list-group-item">@comment.Description</li>
                                }
                            }
                        </ul>
                    </div>
                    <form asp-page-handler="AddComment">
                        <input type="hidden" asp-for="Ticket.History.Id" />
                        <input type="hidden" asp-for="Ticket.Email" />
                        <label class="control-label">Enter Comment</label>
                        <input asp-for="comment.Description" class="form-control" required/>
                        <input type="submit" value="Add Comment" class="btn btn-success mt-1" />
                    </form>
                </div>
            </div>
        </div>
    }
}