CustomerCarePortal/Models/Workflow.cs
namespace CustomerCarePortal.Models
{
    public class Workflow
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? IntialStateId { get; set; }
        public IList<State>? States { get; set; }
        public IList<Ticket>? Tickets { get; set; }
    }
}

CustomerCarePortal/Areas/Identity/Pages/Roles/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CustomerCarePortal.Areas.Identity.Pages.Roles
{
/*    [Authorize(Roles = "Administrator")]
*/    public class DetailsModel : PageModel
    {
        public IList<IdentityUser> AllUsersInSystem { get; set; }
        public IList<IdentityUser> AllUsersInThisRole { get; set; }
        public IdentityRole SelectedRole { get; set; }

        public UserManager<IdentityUser> _usermanager;
        public RoleManager<IdentityRole> _rolemanager;

        public DetailsModel(UserManager<IdentityUser> um, RoleManager<IdentityRole> rm)
        {
            _rolemanager = rm;
            _usermanager = um;
        }




        public async Task<IActionResult> OnGet(string id)
        {
            SelectedRole = _rolemanager.FindByIdAsync(id).Result;


            AllUsersInSystem = _usermanager.Users.ToList();
            AllUsersInThisRole = _usermanager.GetUsersInRoleAsync(SelectedRole.Name).Result;


            return Page();

        }
        public async Task<IActionResult> OnPostAsync(string TaskType, string uid, string rid)
        {

            IdentityRole currentWorkingRole = _rolemanager.FindByIdAsync(rid).Result;
            IdentityUser currentWorkingUser = _usermanager.FindByIdAsync(uid).Result;



            if (TaskType == "AddUser")
            {
                var k = _usermanager.AddToRoleAsync(currentWorkingUser, currentWorkingRole.Name).Result;
            }
            if (TaskType == "RemoveUser")
            {
                var k = _usermanager.RemoveFromRoleAsync(currentWorkingUser, currentWorkingRole.Name).Result;
            }


            return RedirectToAction("", new
            {
                id = rid
            });
        }
    }
}

CustomerCarePortal/Pages/Agents/Create.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CustomerCarePortal.Pages.Agents
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class CreateModel : PageModel
    {
        public IList<IdentityUser> AllUsersInSystem { get; set; } 
        public IList<Team> AllTeamsInSystem { get; set; } = default!;
        [BindProperty]
        public int TeamId { get; set; }
        [BindProperty]
        public string UserId { get; set; }

        public UserManager<IdentityUser> _usermanager;
        private ApplicationDbContext _db;
        public CreateModel(UserManager<IdentityUser> usermanager, ApplicationDbContext db)
        {
            _usermanager = usermanager;
            _db = db;
        }
        public void OnGetAsync()
        {
            AllUsersInSystem =  _usermanager.Users.ToList();
            AllTeamsInSystem = _db.Teams.ToList();
        }

        public async Task<IActionResult> OnPostCreateAgent()
        {
            var user = _usermanager.Users.First(user => user.Id == UserId);
            var team = _db.Teams.FirstOrDefault(team => team.Id == TeamId);
            if (user is not null && team is not null)
            {
                Agent agent = new Agent();
                agent.Name = user.UserName.Split('@')[0];
                agent.Team = team;
                agent.TeamId = team.Id;
                agent.Email = user.Email;
                _db.Agents.Add(agent);
                await _usermanager.AddToRoleAsync(user, "Agent");
                await _db.SaveChangesAsync();
            }
            return Redirect("/Agents/Index");
        }
    }
}

CustomerCarePortal/Pages/Agents/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CustomerCarePortal.Pages.Agents
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;
        [BindProperty]
        public Agent Agent { get; set; }
        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnGetAsync(int? Id)
        {
            if (Id == null || _db.Departments == null)
            {
                return NotFound();
            }

            var agent = await _db.Agents.FirstOrDefaultAsync(a => a.Id == Id);
            if (agent == null)
            {
                return NotFound();
            }
            Agent = agent;
            ViewData["AgentTeams"] = new SelectList(_db.Teams, "Id", "Name");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(Agent is null)
            {
                return Page();
            }

            try
            {
                var team = _db.Teams.FirstOrDefault(t => t.Id == Agent.TeamId);
                if(team is null)
                {
                    return Page();
                }
                else
                {
                    Agent.Team = team;
                }
                _db.Agents.Update(Agent);
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AgentExists(Agent.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AgentExists(int id)
        {
            return (_db.Agents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CustomerCarePortal/Pages/Departments/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;

namespace CustomerCarePortal.Pages.Departments
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class CreateModel : PageModel
    {
        private readonly CustomerCarePortal.Data.ApplicationDbContext _context;

        public CreateModel(CustomerCarePortal.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Department Department { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Departments == null || Department == null)
            {
                return Page();
            }

            _context.Departments.Add(Department);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

CustomerCarePortal/Pages/Departments/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;

namespace CustomerCarePortal.Pages.Departments
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class DeleteModel : PageModel
    {
        private readonly CustomerCarePortal.Data.ApplicationDbContext _context;

        public DeleteModel(CustomerCarePortal.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Department Department { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FirstOrDefaultAsync(m => m.Id == id);

            if (department == null)
            {
                return NotFound();
            }
            else 
            {
                Department = department;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }
            var department = await _context.Departments.FindAsync(id);

            if (department != null)
            {
                Department = department;
                _context.Departments.Remove(Department);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CustomerCarePortal/Pages/Departments/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;

namespace CustomerCarePortal.Pages.Departments
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class DetailsModel : PageModel
    {
        private readonly CustomerCarePortal.Data.ApplicationDbContext _context;

        public DetailsModel(CustomerCarePortal.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Department Department { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            else 
            {
                Department = department;
            }
            return Page();
        }
    }
}

CustomerCarePortal/Pages/Departments/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;

namespace CustomerCarePortal.Pages.Departments
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class EditModel : PageModel
    {
        private readonly CustomerCarePortal.Data.ApplicationDbContext _context;

        public EditModel(CustomerCarePortal.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Department Department { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department =  await _context.Departments.FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            Department = department;
            var validAgents = (from agent in _context.Agents
                                      join team in _context.Teams on agent.TeamId equals team.Id
                                      where team.DepartmentId == Department.Id
                                      select agent);
           ViewData["DepartmentManagers"] = new SelectList(validAgents, "Id", "Name");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Department).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DepartmentExists(Department.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DepartmentExists(int id)
        {
          return (_context.Departments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CustomerCarePortal/Pages/Workflows/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;

namespace CustomerCarePortal.Pages.Workflows
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class EditModel : PageModel
    {
        private readonly CustomerCarePortal.Data.ApplicationDbContext _context;

        public EditModel(CustomerCarePortal.Data.ApplicationDbContext context)
        {
            _context = context;
        }
        [BindProperty]
        public State InitialState { get; set; } = default!;

        [BindProperty]
        public Workflow Workflow { get; set; } = default!;
        [BindProperty]
        public State NewState { get; set; } = default!;
        [BindProperty]
        public Transition NewTransition { get; set; } = default!;
        public List<Transition> Transitions { get; set; } = new List<Transition>();

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Workflows == null)
            {
                return NotFound();
            }

            var workflow = await _context.Workflows.FirstOrDefaultAsync(m => m.Id == id);
            if (workflow == null)
            {
                return NotFound();
            }
            var states = await _context.States.ToListAsync();
            workflow.States = states.FindAll(s => s.Workflow == workflow);
            Workflow = workflow;
            IList<Transition> transitions = await _context.Transitions.ToListAsync();
            foreach(State state in workflow.States)
            {
                foreach(Transition transition in transitions)
                {
                    if(transition.SourceStateId == state.Id)
                    {
                        Transitions.Add(transition);
                    }
                }
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostUpdateWorkflowAsync()
        {
            if (Workflow is null)
            {
                return Page();
            }
            _context.Workflows.Update(Workflow);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WorkflowExists(Workflow.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Edit", new { id = Workflow.Id });
        }

        private bool WorkflowExists(int id)
        {
            return (_context.Workflows?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> OnPostAddStateAsync()
        {
            if (NewState is not null)
            {
                try
                {
                    NewState.Workflow = await _context.Workflows.FirstOrDefaultAsync(w => w.Id == Workflow.Id);
                    await _context.States.AddAsync(NewState);
                    await _context.SaveChangesAsync();

                }
                catch
                {
                    throw;
                }
            }
            return RedirectToPage("./Edit", new { id = Workflow.Id });
        }
        public async Task<IActionResult> OnPostAddTransitionAsync()
        {
            if (NewTransition is not null)
            {
                try
                {
                    await _context.Transitions.AddAsync(NewTransition);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    throw;
                }
            }
            return RedirectToPage("./Edit", new { id = Workflow.Id });
        }

    }
}

CustomerCarePortal/Pages/Workflows/Create.cshtml
@page
@model CustomerCarePortal.Pages.Workflows.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Workflow</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Workflow.Name" class="control-label"></label>
                <input asp-for="Workflow.Name" class="form-control" />
                <span asp-validation-for="Workflow.Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-page="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomerCarePortal/Pages/Workflows/Delete.cshtml
@page
@model CustomerCarePortal.Pages.Workflows.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Workflow</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Workflow.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Workflow.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Workflow.IntialStateId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Workflow.IntialStateId)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Workflow.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

CustomerCarePortal/Pages/Workflows/Details.cshtml
@page
@model CustomerCarePortal.Pages.Workflows.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Workflow</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Workflow.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Workflow.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Workflow.IntialStateId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Workflow.IntialStateId)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Workflow?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

CustomerCarePortal/Pages/Workflows/Edit.cshtml
@page
@model CustomerCarePortal.Pages.Workflows.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Workflow</h4>
<hr />
<div class="row">
    <div class="col-md-5">
        <form class="border p-3 border-dark" method="post" asp-page-handler="UpdateWorkflow">
            <h4>Change Details</h4>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Workflow.Id" />
            <div class="form-group">
                <label asp-for="Workflow.Name" class="control-label"></label>
                <input asp-for="Workflow.Name" class="form-control" />
                <span asp-validation-for="Workflow.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Initial State</label>
                <select asp-for="Workflow.IntialStateId" class="form-control">
                    @if (@Model.Workflow.States is null || @Model.Workflow.States.Count == 0)
                    {
                        <option disabled readonly>No States Added yet</option>
                    }
                    else
                    {
                        @foreach (var item in @Model.Workflow.States)
                        {
                            @if (@Model.Workflow.IntialStateId == item.Id)
                            {
                                <option value="@item.Id" selected>@item.Name</option>
                            }

                            else

                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        }
                    }
                </select>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-page="./Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
    <div class="col-md-2"></div>
    <!-- Here goes the State form-->

    <div class="col-md-4">
        <form class="border p-3 border-dark mt-3" method="post" asp-page-handler="AddState">
            <!-- Adding the State info here -->
            <h4>Add New State</h4>
            <div class="form-group">
                <input type="hidden" asp-for="Workflow.Id" />
                <label asp-for="NewState.Name" class="control-label"></label>
                <input asp-for="NewState.Name" class="form-control" />
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Add State" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div class="row">
    <form class="col-12 border p-3 border-dark my-3" method="post" asp-page-handler="AddTransition">
        <h4>Add New Transition</h4>
        <div class="col-md-8">
            <input type="hidden" asp-for="Workflow.Id" />
            <!--Source Transition-->
            <label asp-for="NewTransition.SourceState" class="control-label"></label>
            <select asp-for="NewTransition.SourceStateId" class="form-control">
                @if (@Model.Workflow.States is not null)
                {
                    @if (@Model.Workflow.States.Count == 0)
                    {
                        <option disabled readonly>No States Added yet</option>
                    }
                    else
                    {
                        @foreach (var item in @Model.Workflow.States)
                        {
                            <option value="@item.Id">@item.Name</option>

                        }
                    }
                }
            </select>

            <!-- Destination State -->

            <label asp-for="NewTransition.DestinationState" class="control-label"></label>
            <select asp-for="NewTransition.DestinationStateId" class="form-control">
                @if (@Model.Workflow.States is not null)
                {
                    @if (@Model.Workflow.States.Count == 0)
                    {
                        <option disabled readonly>No States Added yet</option>
                    }
                    else
                    {
                        @foreach (var state in @Model.Workflow.States)
                        {
                            @if (@Model.Workflow.IntialStateId != state.Id)
                            {
                                <option value="@state.Id">@state.Name</option>
                            }
                        }
                    }
                }
            </select>
        </div>
        <div class="col-md-4">
            <!-- Transition Name -->
            <div class="form-group">
                <label asp-for="NewTransition.Name" class="control-label"></label>
                <input asp-for="NewTransition.Name" class="form-control" />
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Add Transition" class="btn btn-success" />
            </div>
        </div>
    </form>
</div>

<div class="row">
    <h3>Transitions In Workflow</h3>
    <table class="col-12 table table-striped table-hover">
        <thead>
            <tr>
                <th>Source State</th>
                <th>Transition</th>
                <th>Destination State</th>
            </tr>
        </thead>
        <tbody>
            @if (@Model.Transitions is not null)
            {
                @foreach (var tran in @Model.Transitions)
                {
                    <tr>
                        <td>@tran.SourceState.Name</td>
                        <td>@tran.Name</td>
                        <td>@tran.DestinationState.Name</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CustomerCarePortal/Pages/Workflows/Index.cshtml
@page
@model CustomerCarePortal.Pages.Workflows.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<p>
    <a class="btn btn-success" asp-page="Create">Create New Workflow</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Workflow[0].Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Workflow)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>