CustomerCarePortal/Pages/Agents/Create.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CustomerCarePortal.Pages.Agents
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class CreateModel : PageModel
    {
        public IList<IdentityUser> AllUsersInSystem { get; set; } 
        public IList<Team> AllTeamsInSystem { get; set; } = default!;
        [BindProperty]
        public int TeamId { get; set; }
        [BindProperty]
        public string UserId { get; set; }

        public UserManager<IdentityUser> _usermanager;
        private ApplicationDbContext _db;
        public CreateModel(UserManager<IdentityUser> usermanager, ApplicationDbContext db)
        {
            _usermanager = usermanager;
            _db = db;
        }
        public void OnGetAsync()
        {
            AllUsersInSystem =  _usermanager.Users.ToList();
            AllTeamsInSystem = _db.Teams.ToList();
        }

        public async Task<IActionResult> OnPostCreateAgent()
        {
            var user = _usermanager.Users.First(user => user.Id == UserId);
            var team = _db.Teams.FirstOrDefault(team => team.Id == TeamId);
            if (user is not null && team is not null)
            {
                Agent agent = new Agent();
                agent.Name = user.UserName.Split('@')[0];
                agent.Team = team;
                agent.TeamId = team.Id;
                agent.Email = user.Email;
                _db.Agents.Add(agent);
                await _usermanager.AddToRoleAsync(user, "Agent");
                await _db.SaveChangesAsync();
            }
            return Redirect("/Agents/Index");
        }
    }
}

CustomerCarePortal/Pages/Agents/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CustomerCarePortal.Pages.Agents
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;
        [BindProperty]
        public Agent Agent { get; set; }
        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> OnGetAsync(int? Id)
        {
            if (Id == null || _db.Departments == null)
            {
                return NotFound();
            }

            var agent = await _db.Agents.FirstOrDefaultAsync(a => a.Id == Id);
            if (agent == null)
            {
                return NotFound();
            }
            Agent = agent;
            ViewData["AgentTeams"] = new SelectList(_db.Teams, "Id", "Name");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(Agent is null)
            {
                return Page();
            }

            try
            {
                var team = _db.Teams.FirstOrDefault(t => t.Id == Agent.TeamId);
                if(team is null)
                {
                    return Page();
                }
                else
                {
                    Agent.Team = team;
                }
                _db.Agents.Update(Agent);
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AgentExists(Agent.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AgentExists(int id)
        {
            return (_db.Agents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CustomerCarePortal/Pages/Tickets/EditAdmin.cshtml.cs
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CustomerCarePortal.Pages.Tickets
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Administrator")]
    public class EditAdminModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditAdminModel(ApplicationDbContext context)
        {
            _db = context;
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        //For comment section
        public List<Comment> Comments { get; set; } = default!;
        [BindProperty]
        public Comment comment { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _db.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _db.Tickets
                .Include(d => d.TeamAssigned)
                .Include(d => d.History)
                .FirstOrDefaultAsync(t => t.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }
            Comments = await _db.Comments
                        .Where(c => c.HistoryId == ticket.History.Id)
                        .OrderByDescending(c => c.Id)
                        .ToListAsync();
            Ticket = ticket;
            ViewData["Teams"] = new SelectList(_db.Teams, "Id", "Name");
            return Page();
        }
        //OnPost Handler

        public async Task<IActionResult> OnPostAdminHandler()
        {
            if (Ticket is null)
            {
                return Page();
            }

            try
            {
                Ticket.TeamAssigned = _db.Teams.FirstOrDefault(t=>t.Id == Ticket.TeamAssigned.Id);
                _db.Tickets.Update(Ticket);
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(Ticket.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }


        private bool TicketExists(int id)
        {
            return (_db.Agents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> OnPostAddComment()
        {
            try
            {
                if (comment.Description.Trim() != "")
                {
                    string description = DateTime.Now.ToLocalTime().ToString() + ": " + User.Identity.Name.ToString() + ": " + comment.Description;
                    comment.Description = description;
                    comment.HistoryId = Ticket.History.Id;
                    await _db.Comments.AddAsync(comment);
                    await _db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
            return RedirectToPage("./EditAdmin", new { id = Ticket.Id });
        }
    }
}

CustomerCarePortal/Pages/Tickets/EditAgent.cshtml.cs
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CustomerCarePortal.Pages.Tickets
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Agent")]
    public class EditAgentModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditAgentModel(ApplicationDbContext context)
        {
            _db = context;
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;
        //For Transitions
        [BindProperty]
        public Transition Transition { get; set; } = default!;

        //For comment section
        public List<Comment> Comments { get; set; } = default!;
        [BindProperty]
        public Comment comment { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _db.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _db.Tickets
                .Include(d => d.TeamAssigned)
                .Include(d => d.AgentAssigned)
                .Include(d => d.Workflow)
                .Include(d => d.CurrentState)
                .Include(d => d.History)
                .FirstOrDefaultAsync(t => t.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }
            Comments = await _db.Comments
                        .Where(c => c.HistoryId == ticket.History.Id)
                        .OrderByDescending(c => c.Id)
                        .ToListAsync();
            Ticket = ticket;

            var Transitions = await _db.Transitions
                .Where(t => t.SourceStateId == Ticket.CurrentStateId)
                .Select(s => s)
                .ToListAsync();
            ViewData["Transitions"] = new SelectList(Transitions, "Id", "Name");
            return Page();
        }
        //OnPost Handler

        public async Task<IActionResult> OnPostAgentHandler()
        {
            if (Ticket is null)
            {
                return Page();
            }

            try
            {
                Ticket.TeamAssigned = _db.Teams.FirstOrDefault(t => t.Id == Ticket.TeamAssigned.Id);
                Ticket.AgentAssigned = _db.Agents.FirstOrDefault(a => a.Id == Ticket.AgentAssigned.Id);
                Ticket.Workflow = _db.Workflows.FirstOrDefault(w => w.Id == Ticket.WorkflowId);
                Transition = _db.Transitions.FirstOrDefault(t => t.Id == Transition.Id);
                if (Transition is not null)
                {
                    Ticket.CurrentStateId = Transition.DestinationStateId;
                    Ticket.CurrentState = _db.States.FirstOrDefault(s => s.Id == Ticket.CurrentStateId);
                    string com = DateTime.Now.ToLocalTime().ToString() + ": " + User.Identity.Name.ToString() + " Applied transition (" + Transition.Name + ")";
                    Comment comment = new Comment();
                    comment.Description = com;
                    comment.HistoryId = Ticket.History.Id;
                    await _db.Comments.AddAsync(comment);
                }
                _db.Tickets.Update(Ticket);
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(Ticket.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }


        private bool TicketExists(int id)
        {
            return (_db.Agents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> OnPostAddComment()
        {
            try
            {
                if (comment.Description.Trim() != "")
                {
                    string description = DateTime.Now.ToLocalTime().ToString() + ": " + User.Identity.Name.ToString() + ": " + comment.Description;
                    comment.Description = description;
                    comment.HistoryId = Ticket.History.Id;
                    await _db.Comments.AddAsync(comment);
                    await _db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
            return RedirectToPage("./EditAgent", new { id = Ticket.Id });
        }
    }
}

CustomerCarePortal/Pages/Tickets/EditManager.cshtml.cs
using CustomerCarePortal.Data;
using CustomerCarePortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CustomerCarePortal.Pages.Tickets
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "TeamManager")]
    public class EditManagerModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditManagerModel(ApplicationDbContext context)
        {
            _db = context;
        }

        [BindProperty]
        public Ticket Ticket { get; set; } = default!;

        //For comment section
        public List<Comment> Comments { get; set; } = default!;
        [BindProperty]
        public Comment comment { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _db.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _db.Tickets
                .Include(d => d.TeamAssigned)
                .Include(d => d.AgentAssigned)
                .Include(d => d.CurrentState)
                .Include(d => d.Workflow)
                .Include(d => d.History)
                .FirstOrDefaultAsync(t => t.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }
            Comments = await _db.Comments
                        .Where(c => c.HistoryId == ticket.History.Id)
                        .OrderByDescending(c => c.Id)
                        .ToListAsync();
            Ticket = ticket;
            //All agents who are in the team assigned to ticket and is not a manager
            var validAgents = await _db.Agents
                .Where(a => a.TeamId == Ticket.TeamAssigned.Id)
                .Where(a => a.TicketAssinged == null || a.TicketAssinged.Id == Ticket.Id)
                .Where(a => a.Id != Ticket.TeamAssigned.TeamManagerId)
                .Select(s => s).ToListAsync();
            ViewData["Agents"] = new SelectList(validAgents, "Id", "Name");
            ViewData["Workflows"] = new SelectList(_db.Workflows, "Id", "Name");
            return Page();
        }
        //OnPost Handler

        public async Task<IActionResult> OnPostManagerHandler()
        {
            if (Ticket is null)
            {
                return Page();
            }

            try
            {
                Ticket.TeamAssigned = _db.Teams.FirstOrDefault(t => t.Id == Ticket.TeamAssigned.Id);
                //Removing oldAgent ticket and adding new one
                var oldAgent = await _db.Agents
                    .Where(a => a.TicketAssinged != null && a.TicketAssinged.Id == Ticket.Id)
                    .Select(s => s).ToListAsync();
                if (oldAgent is not null && Ticket.AgentAssigned is not null)
                {
                    Agent res = oldAgent[0];
                    //If the agent is changed then update
                    if (res.Id != Ticket.AgentAssigned.Id)
                    {
                        res.TicketAssinged = null;
                        _db.Agents.Update(res);
                    }
                }
                Ticket.AgentAssigned = _db.Agents.FirstOrDefault(a => a.Id == Ticket.AgentAssigned.Id);
                //Attaching workflow
                Ticket.Workflow = _db.Workflows.FirstOrDefault(w => w.Id == Ticket.WorkflowId);
                if (Ticket.CurrentStateId is not null)
                {
                    Ticket.CurrentState = _db.States.FirstOrDefault(s => s.Id == Ticket.CurrentStateId);
                }
                else if (Ticket.Workflow is not null)
                {
                    Ticket.CurrentStateId = Ticket.Workflow.IntialStateId;
                    Ticket.CurrentState = _db.States.FirstOrDefault(s => s.Id == Ticket.CurrentStateId);
                    _db.Tickets.Update(Ticket);
                    await _db.SaveChangesAsync();
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TicketExists(Ticket.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }


        private bool TicketExists(int id)
        {
            return (_db.Agents?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> OnPostAddComment()
        {
            try
            {
                if (comment.Description.Trim() != "")
                {
                    string description = DateTime.Now.ToLocalTime().ToString() + ": " + User.Identity.Name.ToString() + ": " + comment.Description;
                    comment.Description = description;
                    comment.HistoryId = Ticket.History.Id;
                    await _db.Comments.AddAsync(comment);
                    await _db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw;
            }
            return RedirectToPage("./EditManager", new { id = Ticket.Id });
        }
    }
}

CustomerCarePortal/Pages/Tickets/Create.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.CreateModel
@{
    ViewData["Title"] = "Create";
}

<form asp-page-handler="AddTicket">
    <div class=" mb-3">
        <div class="h2 text-primary text-uppercase">Welcome to Ticket Creation Form</div>
        <span class="h4 text-info">Please enter details of the Ticket</span>
    </div>
  <div class="mb-3">
    <label for="CustomerEmail" class="form-label">Email address</label>
    <input type="email" class="form-control" id="CustomerEmail" asp-for=NewTicket.Email>
  </div>
  <div class="mb-3">
      <label for="InputDescription" class="form-label">Enter Description</label>
      <input type="text" class="form-control" id="InputDescription" asp-for=NewTicket.Description placeholder="Enter the details of the ticket"/>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<p>
    <a class="btn btn-primary mt-3"  asp-page="/Tickets/Index">View all Tickets</a>
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomerCarePortal/Pages/Tickets/Edit.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.EditModel
@{
}

CustomerCarePortal/Pages/Tickets/EditAdmin.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.EditAdminModel
@{
}
<h1>Edit</h1>

<h4>Ticket</h4>
<hr />

<div class="row">
    <div class="col-md-6 row" style="margin-right:2px;">
        <div class="col-md-12">
            <form method="post" asp-page-handler="AdminHandler">
                <div class="card border-light mb-3" style="max-width: 100%;">
                    <div class="card-header">Ticket Details</div>
                    <div class="card-body">
                        <h5 class="card-title fw-bolder">@Model.Ticket.Email</h5>
                        <p class="card-text"><b class="fw-bold">Description:</b> @Model.Ticket.Description</p>
                        <p class="card-text">
                            <input type="hidden" asp-for="Ticket.Id" />
                            <input type="hidden" asp-for="Ticket.TrackingId" />
                            <input type="hidden" asp-for="Ticket.Description" />
                            <input type="hidden" asp-for="Ticket.Email" />
                            <!-- Team Assigned-->
                            @if (@Model.Ticket.TeamAssigned is null)
                            {
                                <div class="form-group">
                                    <label class="control-label">Assign Team</label>
                                    <select asp-for="Ticket.TeamAssigned.Id" class="form-select w-50" asp-items="ViewBag.Teams"></select>
                                    <span asp-validation-for="Ticket.TeamAssigned.Id" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-3">
                                    <input type="submit" value="Save" class="btn btn-success" />
                                    <a class="btn btn-primary" asp-page="./Index">Back to List</a>
                                </div>
                            }
                            else
                            {
                                <div class="my-3"><b class="fw-bold">AssignedTeam:</b> @Model.Ticket.TeamAssigned.Name</div>
                                <a class="btn btn-primary" asp-page="./Index">Back to List</a>
                            }
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Comment History-->
    <div class="col-md-6 row">
        <div class="col-12 ">
            <h4>Edit History</h4>
            <div class="card" style="width: 100%;overflow:scroll;height:300px;">
                <ul class="list-group list-group-flush">
                    @if (@Model.Comments is not null)
                    {
                        @foreach (var comment in @Model.Comments)
                        {
                            <li class="list-group-item">@comment.Description</li>
                        }
                    }
                </ul>
            </div>
            <form asp-page-handler="AddComment">
                <input type="hidden" asp-for="Ticket.Id" />
                <input type="hidden" asp-for="Ticket.History.Id" />
                <label class="control-label">Enter Comment</label>
                <input asp-for="comment.Description" class="form-control" />
                <input type="submit" value="Add Comment" class="btn btn-success mt-1" />
            </form>
        </div>
    </div>
</div>

CustomerCarePortal/Pages/Tickets/EditAgent.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.EditAgentModel
@{
}
<h1>Edit</h1>
<br />
<br />

<div class="row">
    <div class="col-md-6 row" style="margin-right:2px;">
        <div class="col-md-12">
            <form method="post" asp-page-handler="AgentHandler">
                <div class="card border-light mb-3" style="max-width: 100%;">
                    <div class="card-header">Ticket Details</div>
                    <div class="card-body">
                        <h5 class="card-title fw-bolder">@Model.Ticket.Email</h5>
                        <p class="card-text"><b class="fw-bold">Description:</b> @Model.Ticket.Description</p>
                        <p class="card-text"><b class="fw-bold">Assigned Team:</b> @Model.Ticket.TeamAssigned.Name</p>
                        <p class="card-text"><b class="fw-bold">Assigned Agent:</b>@Model.Ticket.AgentAssigned.Name</p>
                        <p class="card-text"><b class="fw-bold">Workflow Attached:</b>@Model.Ticket.Workflow.Name</p>
                        <p class="card-text">
                            <input type="hidden" asp-for="Ticket.Id" />
                            <input type="hidden" asp-for="Ticket.TrackingId" />
                            <input type="hidden" asp-for="Ticket.Description" />
                            <input type="hidden" asp-for="Ticket.Email" />
                            <input type="hidden" asp-for="Ticket.TeamAssigned.Id" />
                            <input type="hidden" asp-for="Ticket.AgentAssigned.Id" />
                            <input type="hidden" asp-for="Ticket.History.Id" />
                            <input type="hidden" asp-for="Ticket.CurrentStateId" />
                            <input type="hidden" asp-for="Ticket.WorkflowId" />

                            <!-- Team Assigned-->
                            <div class="form-group">
                                <label class="control-label">Apply Transition</label>
                                <select asp-for="Transition.Id" class="form-select w-50" asp-items="ViewBag.Transitions"></select>
                                <span asp-validation-for="Transition.Id" class="text-danger"></span>
                            </div>

                            <div class="form-group mt-3">
                                <input type="submit" value="Apply Transition" class="btn btn-success" />

                            </div>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Comment History-->
    <div class="col-md-6 row">
        <div class="col-12 ">
            <h4>Edit History</h4>
            <div class="card" style="width: 100%;overflow:scroll;height:300px;">
                <ul class="list-group list-group-flush">
                    @if (@Model.Comments is not null)
                    {
                        @foreach (var comment in @Model.Comments)
                        {
                            <li class="list-group-item">@comment.Description</li>
                        }
                    }
                </ul>
            </div>
            <form asp-page-handler="AddComment">
                <input type="hidden" asp-for="Ticket.History.Id" />
                <input type="hidden" asp-for="Ticket.Id" />
                <label class="control-label">Enter Comment</label>
                <input asp-for="comment.Description" class="form-control" />
                <input type="submit" value="Add Comment" class="btn btn-success mt-1" />
            </form>
        </div>
    </div>
</div>


<div>
    <a class="btn btn-primary" asp-page="./Index">Back to List</a>
</div>

CustomerCarePortal/Pages/Tickets/EditManager.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.EditManagerModel
@{
}

<h1>Edit</h1>
<br />
<br />

<div class="row">
    <div class="col-md-6 row" style="margin-right:2px;">
        <div class="col-md-12">
            <form method="post" asp-page-handler="ManagerHandler">
                <div class="card border-light mb-3" style="max-width: 100%;">
                    <div class="card-header">Ticket Details</div>
                    <div class="card-body">
                        <h5 class="card-title fw-bolder">@Model.Ticket.Email</h5>
                        <p class="card-text"><b class="fw-bold">Description:</b> @Model.Ticket.Description</p>
                        <p class="card-text"><b class="fw-bold">Assigned Team:</b> @Model.Ticket.TeamAssigned.Name</p>
                        <p class="card-text">
                            <!--If Agent is assigned or not-->
                            <b class="fw-bold">Assigned Agent:</b>
                            @if (@Model.Ticket.AgentAssigned is not null)
                            {
                                <text>@Model.Ticket.AgentAssigned.Name</text>
                            }
                            else
                            {
                                <text> Not Assinged</text>
                            }
                        </p>
                        <p class="card-text">
                            <!--If workflow is attached or not-->
                            <b class="fw-bold">Workflow Attached:</b>
                            @if (@Model.Ticket.Workflow is not null)
                            {
                                <text>@Model.Ticket.Workflow.Name</text>
                                <p class="card-text"><b class="fw-bold">Crrent State:</b> @Model.Ticket.CurrentState.Name</p>
                            }
                            else
                            {
                                <text>None</text>
                            }
                        </p>
                        <p class="card-text">
                            <input type="hidden" asp-for="Ticket.Id" />
                            <input type="hidden" asp-for="Ticket.TrackingId" />
                            <input type="hidden" asp-for="Ticket.Description" />
                            <input type="hidden" asp-for="Ticket.Email" />
                            <input type="hidden" asp-for="Ticket.TeamAssigned.Id" />
                            <input type="hidden" asp-for="Ticket.CurrentStateId" />
                            
                            <!-- Team Assigned-->
                            <div class="form-group">
                                <label class="control-label">Assign Agent</label>
                                <select asp-for="Ticket.AgentAssigned.Id" class="form-select w-50" asp-items="ViewBag.Agents"></select>
                                <span asp-validation-for="Ticket.AgentAssigned.Id" class="text-danger"></span>
                            </div>
                            <!-- Workflow Assignment Section-->
                            <!--Worfklow could be attached one time only-->
                            @if (@Model.Ticket.Workflow is null)
                            {
                                <div class="form-group">
                                    <label class="control-label">Attach Workflow</label>
                                    <select asp-for="Ticket.WorkflowId" class="form-select w-50" asp-items="ViewBag.Workflows"></select>
                                    <span asp-validation-for="Ticket.WorkflowId" class="text-danger"></span>
                                </div>
                            }else{
                                <input type="hidden" asp-for="Ticket.WorkflowId" />
                            }
                            <div class="form-group mt-3">
                                <input type="submit" value="Save" class="btn btn-success" />
                                <a class="btn btn-primary" asp-page="./Index">Back to List</a>
                            </div>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Comment History-->
    <div class="col-md-6 row">
        <div class="col-12 ">
            <h4>Edit History</h4>
            <div class="card" style="width: 100%;overflow:scroll;">
                <ul class="list-group list-group-flush">
                    @if (@Model.Comments is not null)
                    {
                        @foreach (var comment in @Model.Comments)
                        {
                            <li class="list-group-item">@comment.Description</li>
                        }
                    }
                </ul>
            </div>
            <form asp-page-handler="AddComment">
                <input type="hidden" asp-for="Ticket.Id" />
                <input type="hidden" asp-for="Ticket.History.Id" />
                <label class="control-label">Enter Comment</label>
                <input asp-for="comment.Description" class="form-control" />
                <input type="submit" value="Add Comment" class="btn btn-success mt-1" />
            </form>
        </div>
    </div>
</div>

CustomerCarePortal/Pages/Tickets/Success.cshtml
@page
@model CustomerCarePortal.Pages.Tickets.SuccessModel
@{
}
<div class="h1 text-info"> Thanks for using the Portal</div>
<div class="h1 text-success">
    Your ticket has been generated with ticket id: @Model.Ticket.TrackingId, We will try to resovle the issue as soon as possible
</div>
<div class="h2 text-info">
    You can check status of your ticket later at <a class="link-info" asp-page="/Tickets/Tracking">Tracking Page</a>
</div>